
### user registration endpoint
POST http://localhost:3001/api/v1/user
Content-Type: application/json

{}

### user get Profile endpoint
GET  http://localhost:3001/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhZGl0MTk5M0BnbWFpbC5jb20iLCJpZCI6IjYxNWRkZDg3ZjM1MjczYjZkMzI1OGQ2MyIsImlhdCI6MTYzMzc4MjE5NSwiZXhwIjoxNjMzNzgzMDk1fQ.1LBFqtt_qdkCiXXmD0dQWXTL0ZBoa0LCW4n4oMqD3ik

### user login endpoint
POST http://localhost:3001/api/v1/user/login
Content-Type: application/json

{
"email": "hadit1993@gmail.com",
"password": "12345678"

}

### reset password endpoint
POST http://localhost:3001/api/v1/user/reset-password
Content-Type: application/json

{
"email": "hadit1993@gmail.com"
}

### update password endpoint
PATCH  http://localhost:3001/api/v1/user/reset-password
Content-Type: application/json

{
"email": "hadit1993@gmail.com",
"pin": "014930",
"newPassword": "123456789"
}

### get token endpoint
GET http://localhost:3001/api/v1/tokens/fresh-access-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhZGl0MTk5M0BnbWFpbC5jb20iLCJpZCI6IjYxNWRkZDg3ZjM1MjczYjZkMzI1OGQ2MyIsImlhdCI6MTYzMzgwNjU0MiwiZXhwIjoxNjM2Mzk4NTQyfQ.W8utC0jhrPZyZMMksvnkMl_iamnH8Pt6OcwOYQuUUM4


